//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageFinalProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalProjectEntities1 : DbContext
    {
        public FinalProjectEntities1()
            : base("name=FinalProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Category { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<Sales> Sales { get; set; }
        public DbSet<WarehouseProducts> WarehouseProducts { get; set; }
        public DbSet<Warehouses> Warehouses { get; set; }
    }
}
